//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 1 files.
  struct file {
    /// Resource file `Service.plist`.
    static let servicePlist = Rswift.FileResource(bundle: R.hostingBundle, name: "Service", pathExtension: "plist")
    
    /// `bundle.url(forResource: "Service", withExtension: "plist")`
    static func servicePlist(_: Void = ()) -> Foundation.URL? {
      let fileResource = R.file.servicePlist
      return fileResource.bundle.url(forResource: fileResource)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    /// Nib `MAFeedViewCell`.
    static let maFeedViewCell = _R.nib._MAFeedViewCell()
    
    /// `UINib(name: "MAFeedViewCell", in: bundle)`
    static func maFeedViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.maFeedViewCell)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `MAFeedViewCell`.
    static let maFeedViewCell: Rswift.ReuseIdentifier<MAFeedViewCell> = Rswift.ReuseIdentifier(identifier: "MAFeedViewCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    struct _MAFeedViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = MAFeedViewCell
      
      let bundle = R.hostingBundle
      let identifier = "MAFeedViewCell"
      let name = "MAFeedViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> MAFeedViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? MAFeedViewCell
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let maDetailViewController = StoryboardViewControllerResource<MADetailViewController>(identifier: "MADetailViewController")
      let maFeedViewController = StoryboardViewControllerResource<MAFeedViewController>(identifier: "MAFeedViewController")
      let name = "Main"
      
      func maDetailViewController(_: Void = ()) -> MADetailViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: maDetailViewController)
      }
      
      func maFeedViewController(_: Void = ()) -> MAFeedViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: maFeedViewController)
      }
      
      static func validate() throws {
        if _R.storyboard.main().maFeedViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'maFeedViewController' could not be loaded from storyboard 'Main' as 'MAFeedViewController'.") }
        if _R.storyboard.main().maDetailViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'maDetailViewController' could not be loaded from storyboard 'Main' as 'MADetailViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
